CREATE DATABASE IF NOT EXISTS IFSP;
USE IFSP;

;
CREATE TABLE IF NOT EXISTS Cidade (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
estado VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Pessoa (
id_pessoa INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
endereco VARCHAR(255) NOT NULL,
bairro VARCHAR(100) NOT NULL,
cep VARCHAR(20) NOT NULL,
id_cidade INT,
FOREIGN KEY (id_cidade) REFERENCES Cidade(id)
);

CREATE TABLE IF NOT EXISTS Animal (
id_animal INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
especie VARCHAR(100) NOT NULL,
raca VARCHAR(100) NOT NULL,
dataN DATE NOT NULL,
idade INT,
id_pessoa INT,
castrado BOOLEAN,
FOREIGN KEY (id_pessoa) REFERENCES Pessoa(id_pessoa)
);

add animal SELECT a.",
           FLOOR(DATEDIFF(CURDATE(), a.dataN)/365) idade
           FROM ANIMAL a;